[package]
name = "treeldr-json-ld-context"
version = "0.1.0"
authors = ["Spruce Systems Inc."]
description = "Schema definition language."
edition = "2021"

[dependencies]
treeldr = { path = "../../core", version = "0.1" }
json-ld = { git = "https://github.com/timothee-haudebourg/json-ld.git", rev = "9366eb7" }
log = "0.4"
iref = "2.2"
serde_json = "1.0"
clap = { version = "3.0", features = ["derive"] }
locspan = "0.7.3"