[package]
name = "treeldr-rust-prelude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = [ "json-ld" ]

[dependencies]
grdf = "0.10"
rdf-types = "0.8.5"
xsd-types = "0.3"
chrono = "0.4.19"
iref = "2.1.3"
static-iref = "2.0.0"
json-ld = { git = "https://github.com/timothee-haudebourg/json-ld.git", rev = "c47ce83", optional = true }