[workspace]
members = [
	"layouts",
	# "layouts/distiller"
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["Spruce Systems Inc."]

[workspace.dependencies]
treeldr-layouts = { path = "layouts/core", version = "0.2.0" }
# treeldr-build = { path = "layouts/build", version = "0.2.0" }

educe = "0.4.23"
num-traits = "0.2"
num-bigint = "0.4"
num-rational = "0.4"
iref = "3.1.3"
static-iref = "3.0"
rdf-types = "0.18.1"
xsd-types = { git = "https://github.com/timothee-haudebourg/xsd-types.git" }
grdf = { version = "0.22.1", features = ["serde"] }
btree-range-map = { version = "0.7.2", features = ["serde"] }
thiserror = "1.0.50"
serde = "1.0.192"

locspan = "0.8.2"
nquads-syntax = "0.17.0"