[workspace]
members = [
	"core",
	"distiller",
	"build"
	# "syntax",
	# "load",
	# "tldrc",
	# "modules/json-schema",
	# "modules/json-ld-context",
	# "modules/rust/gen",
	# "modules/rust/macros",
	# "modules/rust/cli",
	# "modules/rust/prelude",
	# "modules/lexicon"
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["Spruce Systems Inc."]

[workspace.dependencies]
treeldr = { path = "core", version = "0.2.0" }
treeldr-build = { path = "build", version = "0.2.0" }

educe = "0.4.23"
num-rational = "0.4"
iref = "3.1.3"
static-iref = "3.0"
rdf-types = "0.18.1"
xsd-types = "0.8.2"
grdf = "0.22.0"
btree-range-map = "0.7.2"
thiserror = "1.0.50"
serde = "1.0.192"

locspan = "0.8.2"
nquads-syntax = "0.17.0"