[package]
name = "treeldr-cli"
version = "0.1.0"
authors = ["Spruce Systems Inc."]
description = "Schema definition language."
edition = "2021"

[features]
json-schema = [
	"treeldr-json-schema"
]

[dependencies]
treeldr = { path = "../core" }
iref = "2.0"
log = "0.4"
codespan-reporting = "0.11"
stderrlog = "0.5"
clap = { version = "3.0", features = ["derive"] }

# Extensions.
treeldr-json-schema = { path = "../json-schema", version = "0.1", optional = true }

[[bin]]
name = "treeldr"
path = "src/main.rs"