[package]
name = "treeldr"
version = "0.1.0"
authors = ["Spruce Systems Inc."]
description = "Schema definition language."
edition = "2021"

[dependencies]
treeldr-vocab = { path = "../vocab" }
shelves = "0.2.3"
iref = "2.1.2"
iref-enum = "2.0"
static-iref = "2.0"
log = "0.4"
derivative = "2.2.0"
locspan = { version = "0.3.2", features = ["reporting"] }
codespan-reporting = "0.11"
pct-str = "1.1"
rdf-types = { version = "0.4.0", features = ["loc"] }
grdf = { version = "0.7.0", features = ["loc"] }
btree-range-map = "0.2.5"