[package]
name = "treeldr"
version = "0.1.0"
authors = ["Spruce Systems Inc."]
description = "Schema definition language."
edition = "2021"

[features]
bin = [
	"stderrlog",
	"clap"
]

[dependencies]
iref = "2.0"
log = "0.4"
derivative = "*"
locspan = { version = "0.2", features = ["reporting"] }
codespan-reporting = "0.11"

# Command line interface dpendencies.
stderrlog = { version = "0.5", optional = true }
clap = { version = "3.0", features = ["derive"], optional = true }