[package]
name = "treeldr"
version = "0.1.0"
authors = ["Spruce Systems Inc."]
description = "Schema definition language."
edition = "2021"

[dependencies]
treeldr-vocab = { path = "../vocab" }
shelves = "0.2.3"
iref = "2.1.1"
iref-enum = "1.2.0"
static-iref = "1.0.0"
log = "0.4"
derivative = "*"
locspan = { version = "0.3.2", features = ["reporting"] }
codespan-reporting = "0.11"
pct-str = "1.1"
rdf-types = { version = "0.3.6", features = ["loc"] }
grdf = { version = "0.6.1", features = ["loc"] }