[package]
name = "treeldr"
version = "0.1.0"
authors = ["Spruce Systems Inc."]
description = "Schema definition language."
edition = "2021"

[dependencies]
shelves = "0.2.6"
iref = "2.2"
iref-enum = "2.1"
static-iref = "2.0"
log = "0.4"
derivative = "2.2.0"
locspan = { version = "0.7.4", features = ["reporting"] }
locspan-derive = "0.4"
codespan-reporting = "0.11"
rdf-types = { version = "0.9", features = ["meta"] }
xsd-types = "0.3.0"
num = "0.4.0"
grdf = { version = "0.11", features = ["meta"] }
btree-range-map = { version = "0.2.6", features = ["ordered-float"] }
lazy_static = "1.4.0"
ordered-float = "3.0.0"