[package]
name = "treeldr-rust-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
treeldr = { path = "../../../core" }
proc-macro2 = "1.0.40"
quote = "1.0.20"
iref = "2.2"
shelves = "0.2.7"
derivative = "2.2.0"
thiserror = "1.0.31"

[dev-dependencies]
treeldr-rust-macros = { path = "../macros" }
treeldr-rust-prelude = { path = "../prelude" }
chrono = "0.4.19"
iref = "2.2"
grdf = "0.11"
json-ld = { git = "https://github.com/timothee-haudebourg/json-ld.git", rev = "9366eb7" }
json-syntax = "0.8.11"
decoded-char = "0.1"
locspan = "0.7.9"
async-std = { version = "1.12.0", features = ["attributes"] }
log = "0.4.17"
rdf-types = "0.9"