[package]
name = "treeldr-rust-gen"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
treeldr.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn = "2.0.8"
iref.workspace = true
shelves.workspace = true
derivative.workspace = true
thiserror.workspace = true
contextual.workspace = true
rdf-types.workspace = true
locspan.workspace = true