[package]
name = "treeldr-rust-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
treeldr = { path = "../../../core" }
proc-macro2 = "1.0.40"
quote = "1.0.20"
iref = "2.1.3"
shelves = "0.2.7"
derivative = "2.2.0"
thiserror = "1.0.31"

[dev-dependencies]
treeldr-rust-macros = { path = "../macros" }
treeldr-rust-prelude = { path = "../prelude" }
chrono = "0.4.19"
iref = "2.1.3"
grdf = "0.10"
json-ld = { path = "/home/timothee/Projets/utils/rdf/json-ld/json-ld" }
json-syntax = "0.6"
decoded-char = "0.1"
locspan = "0.7.2"
async-std = { version = "1.12.0", features = ["attributes"] }
log = "0.4.17"
rdf-types = "0.8.5"