[package]
name = "treeldr-rust-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
treeldr-rust-macros = { path = "../macros" }