[package]
name = "treeldr-syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
treeldr-vocab = { path = "../vocab" }
iref = "2.1.1"
locspan = "0.3"
codespan-reporting = "0.11"
rdf-types = { version = "0.4.0", features = ["loc"] }

[dev-dependencies]
static-iref = "2.0"
nquads-syntax = "0.2.0"
grdf = "0.7.0"