[package]
name = "treeldr-layouts"
description = "TreeLDR Layouts"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
educe.workspace = true
num-rational.workspace = true
iref = { workspace = true, features = ["serde"] }
rdf-types.workspace = true
xsd-types.workspace = true
grdf = { workspace = true, features = ["meta"] }
btree-range-map.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
serde_json = "1.0"

[dev-dependencies]
rdf-types = { workspace = true, features = ["locspan"] }
static-iref.workspace = true
locspan.workspace = true
nquads-syntax.workspace = true
paste = "1.0"
serde_json = { version = "1.0", features = ["arbitrary_precision"] }